import type { KickstarterExampleDef } from '../../services/example-runner';

export const loanSessionWindowDef: KickstarterExampleDef = {
  id: 'loan-session-window',
  tables: [
    {
      name: 'LOANS',
      schema: 'loans-standard',
      role: 'input',
      dataset: { generator: 'flat-loans', count: 200 },
      stream: 'produce-consume',
    },
    {
      name: 'LOANS-SESSIONS',
      schema: 'loans-sessions',
      role: 'output',
    },
  ],
  sql: [
    {
      label: 'session-window-job',
      sql: `INSERT INTO \`{LOANS-SESSIONS}\`
SELECT
  CAST(CONCAT(customer_id, '-', DATE_FORMAT(session_start, 'yyyy-MM-dd HH:mm:ss')) AS BYTES) AS \`key\`,
  customer_id,
  DATE_FORMAT(session_start, 'yyyy-MM-dd HH:mm:ss') AS session_start,
  DATE_FORMAT(session_end, 'yyyy-MM-dd HH:mm:ss') AS session_end,
  COUNT(*) AS loan_count,
  SUM(amount) AS total_amount,
  CAST(AVG(amount) AS DOUBLE) AS avg_amount
FROM \`{LOANS}\`
GROUP BY customer_id, SESSION($rowtime, INTERVAL '30' SECOND)

-- ============================================================
-- WHAT: Groups loans per customer into SESSION windows — bursts of activity separated by 30s of silence.
-- SESSION WINDOW: Dynamic, not fixed. Stays open while events arrive within the gap. Closes after 30s inactivity.
-- WHY SESSION vs TUMBLE/HOP: Sessions model user behavior ("how many loans in one burst?"). Fixed windows ignore activity patterns.
-- WHY GROUP BY customer_id, SESSION(...): Sessions are tracked PER customer. session_start/session_end are auto-generated by Flink.
-- WHY composite key: customer_id + session_start uniquely identifies each session for Kafka partitioning and compaction.
-- GOTCHA: Sessions emit ONLY after the 30s gap elapses — slowest window type. Wait at least 30s of inactivity for results.
-- GOTCHA: Continuous data with no gaps > 30s means the session never closes — can cause high memory. Consider max session duration in production.
-- ============================================================`,
    },
    {
      label: 'view-output',
      sql: `SELECT * FROM \`{LOANS-SESSIONS}\` LIMIT 50

-- ============================================================
-- WHAT: Reads per-customer session aggregates from LOANS-SESSIONS — one row per activity burst.
-- GOTCHA: Session windows are the slowest to emit. Wait at least 30s of inactivity after the last event.
-- ============================================================`,
    },
  ],
  completionModal: {
    subtitle: 'Your workspace is ready. Follow these steps to run the example:',
    steps: [
      { label: 'Produce test data', detail: 'Click \u25b6 on the LOANS stream card to send 200 loan records.' },
      { label: 'Run session window job', detail: 'Run the INSERT INTO cell; the job groups loan applications by customer activity bursts with a 30-second gap.' },
      { label: 'Wait ~30 seconds', detail: 'Sessions close when the idle gap exceeds 30 seconds.' },
      { label: 'View sessions', detail: 'Run the SELECT * LIMIT 50 cell to see session aggregates per customer.' },
    ],
  },
};
